apiVersion: v1
kind: ConfigMap
metadata:
  name: kfn-copy-function-config
  namespace: default
data:
  function.properties: |-
    consumer.bootstrap.servers=kafka-headless:9092
    consumer.group.id=copy-function
    consumer.auto.offset.reset=earliest
    consumer.key.deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer
    consumer.value.deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer

    producer.bootstrap.servers=kafka-headless:9092
    producer.acks=all
    producer.retries=3
    producer.key.serializer=org.apache.kafka.common.serialization.ByteArraySerializer
    producer.value.serializer=org.apache.kafka.common.serialization.ByteArraySerializer

    function.name=copy-function
    function.class=io.dajac.kfn.functions.CopyFunction
    function.input=dajac.dev.input
    function.output=dajac.dev.output
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kfn-copy-function
  labels:
    app: kfn-copy-function
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kfn-copy-function
  template:
    metadata:
      labels:
        app: kfn-copy-function
    spec:
      containers:
      - name: kfn-invoker
        image: dajac/kfn-invoker:0.1.0
        imagePullPolicy: Always
        command:
          - /usr/bin/java
          - -cp
          - /usr/lib/kfn/*
          - io.dajac.kfn.invoker.FunctionInvoker
          - /etc/kfn/function.properties
        volumeMounts:
        - name: config-vol
          mountPath: /etc/kfn
      volumes:
      - name: config-vol
        configMap:
          name: kfn-copy-function-config
          items:
          - key: function.properties
            path: function.properties